config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'destinations#home'
  get 'primeiro_destino', to: 'destinations#primeiro_destino'
  get 'segundo_destino', to: 'destinations#segundo_destino'
  get 'user', to: 'destinations#user'
  get 'rank/:id', to: 'destinations#rank', as: :rank 
  post 'create_user', to: 'destinations#create_user'
  patch 'up-vote', to: 'destinations#up_vote'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :votersession
  validates :name, presence: true 
  validates :email, format: { with: /\A.*@.*\.com\z/ }
end

app/models/votersession.rb
class Votersession < ApplicationRecord
  belongs_to :user, optional: true
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :load_destinations, only: [:primeiro_destino, :segundo_destino, :rank]
  before_action :set_voter, only: [:up_vote]

  def home
  end

  def primeiro_destino
    @first_choices = @destinations.first(2)
  end
  
  def segundo_destino
    @second_choices = @destinations.last(3)
  end

  def user
    @user = User.new
  end

  def up_vote
    destino = Destination.find(destination_params[:id])
    destino.vote_by voter: @voter, :duplicate => true
    if request.headers["referer"].include?("primeiro_destino")
      
      redirect_to segundo_destino_path
    elsif request.headers["referer"].include?("segundo_destino")

      redirect_to user_path
    else
      
      render :home
    end
  end

  def create_user
    user = User.new(user_params)

    if User.exists?(user_params)
      user = User.find_by(user_params)
      confirm_vote(user)

      return redirect_to rank_path user
    end

    if user.save
      confirm_vote(user)
      
      return redirect_to rank_path user
    else
      flash[:error] = user.errors
      return redirect_to user_path
    end
  end

  def rank
    voted_items = []
    sessions = Votersession.where(user_id: params[:id])
    sessions.each do |session|
      voted_items << session.find_voted_items
    end

    @destinos = voted_items
                .flatten
                .group_by{ |i| i }
                .map{ |k,v| [k.name, v.count] }.to_h
  end

  private

  def confirm_vote(user)
    Votersession.last(2).each{ |session| session.update(user_id: user.id) }
  end

  def set_voter
    @voter = Votersession.create!(
      session_id: request.session_options[:id].to_s
    )
  end

  def load_destinations
    @destinations = Destination.all
  end

  def destination_params
    params.require(:destination).permit(:id)
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/home.html.erb
<div class="container">
  <h1>Vote no seu destino de viagem favorito! 🚀</h1>

  <%= link_to 'Iniciar', primeiro_destino_path, class:"btn btn-primary btn-lg" %>
</div>

app/views/destinations/primeiro_destino.html.erb
<div class="container">
  <h2>Qual destes lugares você gosta mais?</h2>

  <%= simple_form_for @first_choices, url: up_vote_path do |f| %>

    <%= f.input :id, label: '', as: :radio_buttons, collection: @first_choices %>

    <%= f.button :submit, 'Votar', class:"btn btn-primary btn-lg" %>
    
  <% end %>
</div>

app/views/destinations/rank.html.erb
<div class="container">
  <h2>Rank Geral</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Destino</th>
        <th scope="col">Votos</th>
      </tr>
    </thead>
    <tbody>
    <% @destinations.each do |destino| %>
      <tr>
        <td><%= destino.name %></td>
        <td><%= destino.votes_for.count %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
  <h2>Seu votos</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Destino</th>
        <th scope="col">Votos</th>
      </tr>
    </thead>
    <tbody>
    <% @destinos.each do |destino, votos| %>
      <tr>
        <td><%= destino %></td>
        <td><%= votos %></td>
      </tr>
    <% end %>
    </tbody>
  </table>  

  <%= link_to 'Home', root_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/destinations/segundo_destino.html.erb
<div class="container">
<h2>Destes outros qual você gostaria de conhecer?</h2>
  <%= simple_form_for @second_choices, url: up_vote_path do |f| %>

    <%= f.input :id, label: '', as: :radio_buttons, collection: @second_choices %>

    <%= f.button :submit, 'Votar', class:"btn btn-primary btn-lg" %>
    
  <% end %>
</div>

app/views/destinations/user.html.erb
<div class="container">
  <% unless flash.blank? %>
    <% flash.each do |error, msg| %>
      <div class="alert alert-danger" role="alert">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <h2>Informe seus dados confirmarmos o voto</h2>

  <%= simple_form_for @user, url: create_user_path do |f| %>
    <%= f.error_notification %>
    <%= f.full_error :confirmation_token %>

    <%= f.input :name, required: true %>

    <%= f.input :email, 
                input_html: { autocomplete: 'email' }, 
                required: true %>

    <%= f.button :submit, "Confirmar", class: "btn btn btn-success btn-lg" %>
  <% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteNoDestino</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>